# Generated by Django 2.2.28 on 2022-10-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagemeta', '0002_auto_20220917_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaforpage',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metaforpage',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metaforpage',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='page-meta/', verbose_name='Image', width_field='image_width'),
        ),
    ]
