# Generated by Django 2.2.28 on 2022-10-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagemeta', '0003_auto_20221002_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metaforpage',
            options={'ordering': ('-id',), 'verbose_name': 'Meta for Page', 'verbose_name_plural': 'Meta for Pages'},
        ),
    ]
